dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/ffmpeg-4'
    packages:
    - qt5-default
    - libjack-jackd2-dev
    - libsamplerate0-dev
    - libasound2-dev
    - qtmultimedia5-dev
    - libqt5multimedia5-plugins
    - libqt5sql5-sqlite
    - libboost-all-dev
    - libfftw3-dev
    - yasm
    - libavformat-dev
    - libavcodec-dev
    - libavutil-dev
    - libswresample-dev

before_install:
  - git clone https://github.com/jrosener/libKeyFinder.git
  - cd libKeyFinder
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -S .
  - sudo env "PATH=$PATH" cmake --build . --target install
  - cd ..

script:
  - cd libdigitalscratch && qmake && make && sudo make install
  - make clean && qmake CONFIG+=test && make
  - ./libdigitalscratch-test
  - cd ..
  - cd digitalscratch && qmake && make
  - make clean && qmake CONFIG+=test-no_device_test && make
  - ./digitalscratch-test
